runtime: php
env: flex
api_version: 1

manual_scaling:
  instances: 1


beta_settings:
  cloud_sql_instances: "text-402508:us-central1:text2"

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "8.3"
    document_root: .

handlers:
- url: /upload/(.+\.png)
  static_files: upload/\1
  upload: upload/.+\.png

- url: /upload/(.+\.jpg)
  static_files: upload/\1
  upload: upload/.+\.jpg

- url: /upload/(.+\.PNG)
  static_files: upload/\1
  upload: upload/.+\.PNG

- url: /upload/(.+)
  static_files: upload/\1
  upload: upload/.+

- url: /.*
  script: auto



env_variables:
  GOOGLE_STORAGE_BUCKET: "text-402508.appspot.com"
  MYSQL_DSN: "mysql:unix_socket:/cloudsql/text-402508:us-central1:text2;dbname=text3"
  MYSQL_PORT: "3306"
  MYSQL_DB: "text3"
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "12345678"
